### PR TITLE
adds local settings semantics, and file

### PR DESCRIPTION
**Pull request by semafor**
Fixes https://github.com/FriskByBergen/python-friskby/issues/8

More specifically:
- Adds a rpiparticle package with a `fby_settings` module. This ensures that arbitrary python modules can read our settings.
- Adds `friskby-settings.json`
- Sets settings for sampler, friskby, submitter and control panel

### CODE REVIEW

**Review by pgdr — APPROVED** [review]
We could've had testing, with the settings path able to being overridden by an environment variable, but not crucial.

We could've had a test for whether the file exists and if not, create it, but again not crucial.

We could finally take use of the RPiParticle initial file to import get_settings etc, but I don't know if that's a good idea.

**Comment by semafor** [comment]
> We could've had a test for whether the file exists and if not, create it, but again not crucial.

Test for what file?

> We could finally take use of the RPiParticle initial file to import get_settings etc, but I don't know if that's a good idea.

Could you expand on that?

**Comment by semafor** [comment]
This branch will fix issue #118 as well.

**Comment by pgdr** [comment]
>> We could've had a test for whether the file exists and if not, create it, but again not crucial.

> Test for what file?

The settings file.  If it doesn't exist, then `fby_settings` will crash unnecessarily hard.

>> We could finally take use of the RPiParticle initial file to import get_settings etc, but I don't know if that's a good idea.

> Could you expand on that?

If `rpiparticle` is a module, then the `__init.py__` file should import the exposed functionality and define `__VERSION__ = '0.7.2'` or what it is now.  In addition, we could expose the _functions_ from `fby_settings` so we can call `from rpiparticle import get_settings; get_settings(...)`.


Ps., a test could include running pylint on the `rpiparticle` files, which could/would/should catch some bugs.

**Comment by pgdr** [comment]
But in any way; LGTM, merge

**Comment by semafor** [comment]
> The settings file. If it doesn't exist, then fby_settings will crash unnecessarily hard.

Yes, good point. Created issue #120.

**Pull request merged**
