### PR TITLE
Accept non existent settings

### PR DESCRIPTION
**Pull request by semafor**
* Drops the settings file from the package
* Reads either from disk (known location) or from local, “immutable” file used as merely a provider of defaults
* Provides ability to write to the settings file

### CODE REVIEW

**Comment by semafor** [comment]
Tests are failing for me in master as well.

**Comment by semafor** [comment]
Note to self: Needs to make sure that the package being built ships.

**Comment by semafor** [comment]
I think this is now out of WIP.

**Review by pgdr — APPROVED** [review]
LGTM!

**Pull request merged**
